import Head from 'next/head';
import React from 'react';

export default function route() {
  return (
    <>
      <Head>
        <title>ML JEWELLERS | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex justify-center items-center">
        <h1>route</h1>
      </main>
    </>
  );
}
