import Head from 'next/head';

import Button from '@mui/material/Button';
import { ReactElement } from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>ML LOANS | LOGIN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1>Login Page</h1>
      </main>
    </>
  );
}

Home.getLayout = function PageLayout(page: ReactElement) {
  return <>{page}</>;
};
